language: java
script: ./gradlew build -s
jdk:
  - oraclejdk8
# Caching for Gradle files, prevents hitting Maven too much.
before_cache:
  - find $HOME/.gradle -name '*.lock' -print -exec rm -f {} \;
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Faster builds without sudo.
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
# Code Coverage!
before_install:
  - pip install --user codecov
after_success:
  - codecov
after_script:
  # Make sure to kill daemon
  - ./gradlew --stop
